plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
	id 'me.modmuss50.mod-publish-plugin' version '0.5.1'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
	//implementation "curse.maven:yogmod-372408:8599632"
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

publishMods {
    file = tasks.jar.archiveFile

    changelog = providers.environmentVariable("RELEASE_CHANGELOG").orElse("No changelog provided.")
    type = STABLE

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = "1201454"
        minecraftVersions.add("1.20.1")
        clientRequired = true
        serverRequired = true
        modLoaders.add("neoforge")

        displayName = "NeoForge - ${project.version} - ${project.minecraft_version}"

        optional {
            slug = "yogmod"
        }
    }
}

tasks.named('jar') {
    archiveFileName = "${project.mod_id}-neoforge-${project.version}-${project.minecraft_version}.jar"
}

tasks.named('sourcesJar') {
    archiveFileName = "${project.mod_id}-neoforge-${project.version}-${project.minecraft_version}-sources.jar"
}

tasks.named('javadocJar') {
    archiveFileName = "${project.mod_id}-neoforge-${project.version}-${project.minecraft_version}-javadoc.jar"
}
